### PR TITLE
Er 122 app icons

### PR DESCRIPTION
**Pull request by BryceV**
Added icons for phone screens. IOS users need to still verify this works. Tested already on my Nexus API 28 android emulator.

### CODE REVIEW

**Comment by smrizzo** [comment]
So just pulled this down and tried to run it. It doesn't currently work on IOS and all I have to give you is this error message which isn't that useful.

As of right now though if I switch to this branch the app breaks so will have to figure this error out.

Screen Shot 2019-05-11 at 4 16 09 PM

**Comment by BryceV** [comment]
Ok, I was afraid of this IOS issue. All the instructions I found had XCode magically linking the icon throughout the project. I might need someone with XCode to take it the last 10%. 

1) Save a copy of  .\AmazonHandMade\ios\AmazonHandmadeRN\Images.xcassets because it has all the images (some inside the "AppIcon.appiconset" folder and some not)
2) Do a git reset on .\AmazonHandMade\ios\AmazonHandmadeRN\Images.xcassets and notice the differences
3) Do the bottom step listed here https://aboutreact.com/react-native-change-app-icon/ with the images

**Comment by smrizzo** [comment]
So when looking in that folder via Finder there is no images. Just a .json file?

It's saying it want's me to drag and drop actual image files, .png etc 

Also when I did a git reset nothing really happened from what I could see.

**Comment by BryceV** [comment]
Just verified the images are in the folders. Double check the path.

**Comment by smrizzo** [comment]
Yeah was my mistake. I pulled down your other branch so let me start this process over

**Comment by smrizzo** [comment]
Okay so after loading this up it all seems to be working. I opened up project in Xcode and all the images are there in app icons under Images.xcassets folder. 

 I now see the icon on the emulator for the device I have chosen. I won't be able to test this on my actual phone till later.

**Comment by BryceV** [comment]
Yeah thats about it. This should just be a simple put them in and they show up on the device PR.

**Review by smrizzo — APPROVED** [review]
Everything seems to be working as expected. I was able to see the new icon in emulator for iOS.

**Pull request merged**
